package Model.GeneratedPlayList;

import Model.PlayList.PlayList;
import Model.Song.Song;
import Model.Song.Сharacteristic.*;

public class GeneratedPlayList extends PlayList {

    public static PlayList SongGenerator(){

        Song song1 = new Song("Summer Megamix 2005","Best Of","Benassi Bros, Dhany, Sandy",255, Language.ENGLISH, Genre.ELECTRONIC, Feeling.ENERGETICALLY, Action.PARTY, 2005, Temp.FAST, Group_size.TRIO);
        Song song2 = new Song("Verbatim","Touch Up","Mother Mother",168, Language.ENGLISH, Genre.INDY, Feeling.DREAMY, Action.LEARNING, 2007, Temp.MEDIUM, Group_size.QUINTET);
        Song song3 = new Song("Hay Loft","O My Heart"," Mother Mother",181, Language.ENGLISH, Genre.INDY, Feeling.ENERGETICALLY, Action.TRAINING, 2008, Temp.FAST, Group_size.QUINTET);
        Song song4 = new Song("Hayloft II","Inside"," Mother Mother",215, Language.ENGLISH, Genre.INDY, Feeling.ENERGETICALLY, Action.DRIVING, 2022, Temp.MEDIUM, Group_size.QUINTET);
        Song song5 = new Song("Weep","Inside"," Mother Mother",207, Language.ENGLISH, Genre.INDY, Feeling.CALM, Action.WORKING, 2022, Temp.SLOW, Group_size.QUINTET);
        Song song6 = new Song("Teenagers","The Black Parade / Living with GhostsThe 10th Anniversary Edition","My Chemical Romance",161, Language.ENGLISH, Genre.ROCK, Feeling.ENERGETICALLY, Action.DRIVING, 2016, Temp.MEDIUM, Group_size.QUINTET);
        Song song7 = new Song("The Sharpest Lives","The Black Parade / Living with GhostsThe 10th Anniversary Edition","My Chemical Romance",200, Language.ENGLISH, Genre.ROCK, Feeling.ENERGETICALLY, Action.TRAINING, 2016, Temp.FAST, Group_size.QUINTET);
        Song song8 = new Song("Famous Last Words","The Black Parade / Living with GhostsThe 10th Anniversary Edition","My Chemical Romance",299, Language.ENGLISH, Genre.ROCK, Feeling.DREAMY, Action.LEARNING, 2016, Temp.MEDIUM, Group_size.QUINTET);
        Song song9 = new Song("Na Na Na (Na Na Na Na Na Na Na Na Na)","May Death Never Stop You","My Chemical Romance",206,Language.ENGLISH, Genre.ROCK, Feeling.ENERGETICALLY, Action.DRIVING, 2014, Temp.FAST, Group_size.QUINTET);
        Song song10 = new Song("I'm Not Okay (I Promise)","Three Cheers for Sweet Revenge","My Chemical Romance",188, Language.ENGLISH, Genre.ROCK, Feeling.SADLY, Action.SLEEPING, 2004, Temp.FAST, Group_size.QUINTET);
        Song song11 = new Song("Helena","Three Cheers for Sweet Revenge","My Chemical Romance",204, Language.ENGLISH, Genre.ROCK, Feeling.ENERGETICALLY, Action.LEARNING, 2004, Temp.FAST, Group_size.QUINTET);
        Song song12 = new Song("You Know What They Do to Guys Like Us in Prison","Three Cheers for Sweet Revenge","My Chemical Romance",173, Language.ENGLISH, Genre.ROCK, Feeling.ENERGETICALLY, Action.DRIVING, 2004, Temp.FAST, Group_size.QUINTET);
        Song song13 = new Song("Царица","Царица","ANNA ASTI",215, Language.RUSSIAN, Genre.DANCE, Feeling.ENERGETICALLY, Action.PARTY, 2023, Temp.MEDIUM, Group_size.SOLO);
        Song song14 = new Song("Седьмой лепесток","Седьмой лепесток","Антон Токарев",199, Language.RUSSIAN, Genre.POP, Feeling.SADLY, Action.NOSTALGIA, 2021, Temp.SLOW, Group_size.SOLO);
        Song song15 = new Song("Огни","Огни","ANIKV, SALUKI",206, Language.RUSSIAN, Genre.POP, Feeling.ENERGETICALLY, Action.DRIVING, 2022, Temp.FAST, Group_size.DUO);
        Song song16 = new Song("Покинула чат","Покинула чат","Клава Кока",173, Language.RUSSIAN, Genre.DANCE, Feeling.ENERGETICALLY, Action.PARTY, 2020, Temp.FAST, Group_size.SOLO);
        Song song17 = new Song("Плачу на техно","Плачу на техно","CREAM SODA, ХЛЕБ",219, Language.RUSSIAN, Genre.POP, Feeling.ENERGETICALLY, Action.PARTY, 2020, Temp.FAST, Group_size.SOLO);
        Song song18 = new Song("Nothing's Gonna Change My Love for You","The Ultimate Collection","George Benson",241, Language.ENGLISH, Genre.POP, Feeling.DREAMY, Action.NOSTALGIA, 1985, Temp.SLOW, Group_size.SOLO);
        Song song19 = new Song("Perfect","÷","Ed Sheeran",263, Language.ENGLISH, Genre.POP, Feeling.DREAMY, Action.SLEEPING, 2017, Temp.SLOW, Group_size.SOLO);
        Song song20 = new Song("Shape of You","÷","Ed Sheeran",233, Language.ENGLISH, Genre.POP, Feeling.ENERGETICALLY, Action.WORKING, 2017, Temp.MEDIUM, Group_size.SOLO);
        Song song21 = new Song("Sorry Seems To Be The Hardest Word","Diamonds","Elton John",230, Language.ENGLISH, Genre.POP, Feeling.DREAMY, Action.NOSTALGIA, 1985, Temp.SLOW, Group_size.SOLO);
        Song song22 = new Song("Believe","Diamonds","Elton John",292, Language.ENGLISH, Genre.POP, Feeling.CALM, Action.LEARNING, 1995, Temp.SLOW, Group_size.SOLO);
        Song song23 = new Song("I'm Still Standing","Diamonds","Elton John",182, Language.ENGLISH, Genre.POP, Feeling.ENERGETICALLY, Action.DRIVING, 1985, Temp.FAST, Group_size.SOLO);
        Song song24 = new Song("Kiss The Bride","Diamonds","Elton John",263, Language.ENGLISH, Genre.POP, Feeling.ENERGETICALLY, Action.WORKING, 1983, Temp.MEDIUM, Group_size.SOLO);
        Song song25 = new Song("No Roots","MINT +4","Alice Merton",235, Language.ENGLISH, Genre.POP, Feeling.ENERGETICALLY, Action.WORKING, 2019, Temp.MEDIUM, Group_size.SOLO);
        Song song26 = new Song("Papaoutai","Racine Carrée","Stromae",231, Language.FRENCH, Genre.ELECTRONIC, Feeling.SADLY, Action.NOSTALGIA, 2013, Temp.MEDIUM, Group_size.SOLO);
        Song song27 = new Song("Tous Les Mêmes","Racine Carrée","Stromae",213, Language.FRENCH, Genre.ELECTRONIC, Feeling.ENERGETICALLY, Action.PARTY, 2013, Temp.MEDIUM, Group_size.SOLO);
        Song song28 = new Song("Formidable","Racine Carrée","Stromae",214, Language.FRENCH, Genre.ELECTRONIC, Feeling.SADLY, Action.LEARNING, 2013, Temp.MEDIUM, Group_size.SOLO);
        Song song29 = new Song("Bohemian Rhapsody","A Night at the Opera","Queen",354, Language.ENGLISH, Genre.ROCK, Feeling.EPIC, Action.DRIVING, 1975, Temp.FAST, Group_size.QUARTET);
        Song song30 = new Song("Take Five","Time Out","The Dave Brubeck Quartet",324, Language.INSTRUMENTAL, Genre.JAZZ, Feeling.CALM, Action.LEARNING, 1959, Temp.MEDIUM, Group_size.QUARTET);
        Song song31 = new Song("Le Festin","Ratatouille Soundtrack","Camille",186, Language.FRENCH, Genre.POP, Feeling.HAPPY, Action.NOSTALGIA, 2007, Temp.FAST, Group_size.SOLO);
        Song song32 = new Song("Du Hast","Sehnsucht","Rammstein",241, Language.GERMAN, Genre.METAL, Feeling.AGGRESSIVE, Action.TRAINING, 1997, Temp.MEDIUM, Group_size.QUINTET);
        Song song33 = new Song("Gangnam Style","Psy 6 (Six Rules), Part 1","PSY",219, Language.KOREAN, Genre.POP, Feeling.ENERGETICALLY, Action.PARTY, 2012, Temp.MEDIUM, Group_size.SOLO);
        Song song34 = new Song("La Vie en Rose","Chansons d'Amour","Édith Piaf",211, Language.FRENCH, Genre.CLASSIC, Feeling.DREAMY, Action.SLEEPING, 1945, Temp.SLOW, Group_size.SOLO);
        Song song35 = new Song("Despacito","Vida","Luis Fonsi ft. Daddy Yankee",228, Language.SPANISH, Genre.POP, Feeling.HAPPY, Action.PARTY, 2017, Temp.MEDIUM, Group_size.DUO);
        Song song36 = new Song("Smells Like Teen Spirit","Nevermind","Nirvana",301, Language.ENGLISH, Genre.ROCK, Feeling.ENERGETICALLY, Action.TRAINING, 1991, Temp.MEDIUM, Group_size.TRIO);
        Song song37 = new Song("Faded","Faded","Alan Walker",212, Language.ENGLISH, Genre.ELECTRONIC, Feeling.MYSTICALLY, Action.DRIVING, 2015, Temp.MEDIUM, Group_size.SOLO);
        Song song38 = new Song("7 Years","Lukas Graham","Lukas Graham",237, Language.ENGLISH, Genre.POP, Feeling.CALM, Action.NOSTALGIA, 2015, Temp.MEDIUM, Group_size.QUARTET);
        Song song39 = new Song("All the Stars","Black Panther: The Album","Kendrick Lamar ft. SZA",234, Language.ENGLISH, Genre.HIPHOP, Feeling.EPIC, Action.WORKING, 2018, Temp.MEDIUM, Group_size.DUO);
        Song song40 = new Song("Moonlight Sonata",null,"Ludwig van Beethoven",376, Language.INSTRUMENTAL, Genre.CLASSIC, Feeling.CALM, Action.SLEEPING, 1801, Temp.SLOW, Group_size.SOLO);
        Song song41 = new Song("Creep","Pablo Honey","Radiohead",236, Language.ENGLISH, Genre.ROCK, Feeling.SADLY, Action.NOSTALGIA, 1992, Temp.SLOW, Group_size.QUINTET);
        Song song42 = new Song("Voyager","Random Access Memories","Daft Punk",249, Language.ENGLISH, Genre.ELECTRONIC, Feeling.MYSTICALLY, Action.DRIVING, 2013, Temp.MEDIUM, Group_size.DUO);
        Song song43 = new Song("Lose Yourself","8 Mile Soundtrack","Eminem",326, Language.ENGLISH, Genre.RAP, Feeling.AGGRESSIVE, Action.TRAINING, 2002, Temp.FAST, Group_size.SOLO);
        Song song44 = new Song("No Surprises","OK Computer","Radiohead",227, Language.ENGLISH, Genre.ROCK, Feeling.CALM, Action.SLEEPING, 1997, Temp.SLOW, Group_size.QUINTET);
        Song song45 = new Song("Toccata and Fugue in D Minor",null,"Johann Sebastian Bach",508, Language.INSTRUMENTAL, Genre.CLASSIC, Feeling.EPIC, Action.LEARNING, 1703, Temp.SLOW, Group_size.SOLO);
        Song song46 = new Song("Street Spirit (Fade Out)","The Bends","Radiohead",273, Language.ENGLISH, Genre.ROCK, Feeling.DREAMY, Action.NOSTALGIA, 1995, Temp.SLOW, Group_size.QUINTET);
        Song song47 = new Song("Für Elise",null,"Ludwig van Beethoven",170, Language.INSTRUMENTAL, Genre.CLASSIC, Feeling.CALM, Action.WORKING, 1810, Temp.FAST, Group_size.SOLO);
        Song song48 = new Song("Smooth Criminal","Bad","Michael Jackson",269, Language.ENGLISH, Genre.POP, Feeling.ENERGETICALLY, Action.PARTY, 1988, Temp.MEDIUM, Group_size.SOLO);
        Song song49 = new Song("Sweet Child o' Mine","Appetite for Destruction","Guns N' Roses",355, Language.ENGLISH, Genre.ROCK, Feeling.ENERGETICALLY, Action.DRIVING, 1987, Temp.MEDIUM, Group_size.QUINTET);
        Song song50 = new Song("Hymn for the Weekend","A Head Full of Dreams","Coldplay",259, Language.ENGLISH, Genre.POP, Feeling.HAPPY, Action.PARTY, 2015, Temp.FAST, Group_size.SOLO);
        Song song51 = new Song("November Rain","Use Your Illusion I","Guns N' Roses",537, Language.ENGLISH, Genre.ROCK, Feeling.EPIC, Action.NOSTALGIA, 1991, Temp.SLOW, Group_size.QUINTET);
        Song song52 = new Song("Send My Love (To Your New Lover)","25","Adele",217, Language.ENGLISH, Genre.POP, Feeling.HAPPY, Action.WORKING, 2015, Temp.MEDIUM, Group_size.SOLO);
        Song song53 = new Song("Nothing Else Matters","Metallica","Metallica",388, Language.ENGLISH, Genre.ROCK, Feeling.CALM, Action.SLEEPING, 1991, Temp.SLOW, Group_size.QUINTET);
        Song song54 = new Song("Comptine d'un autre été: L'après-midi","Amélie (Soundtrack)","Yann Tiersen",95, Language.INSTRUMENTAL, Genre.CLASSIC, Feeling.DREAMY, Action.NOSTALGIA, 2001, Temp.SLOW, Group_size.SOLO);
        Song song55 = new Song("Hotel California","Hotel California","Eagles",391, Language.ENGLISH, Genre.ROCK, Feeling.CALM, Action.DRIVING, 1976, Temp.SLOW, Group_size.QUINTET);
        Song song56 = new Song("Love Me Like You Do","Fifty Shades of Grey (Soundtrack)","Ellie Goulding",252, Language.ENGLISH, Genre.POP, Feeling.DREAMY, Action.NOSTALGIA, 2015, Temp.MEDIUM, Group_size.SOLO);
        Song song57 = new Song("Smooth","Smooth","Santana ft. Rob Thomas",364, Language.ENGLISH, Genre.ROCK, Feeling.HAPPY, Action.PARTY, 1999, Temp.MEDIUM, Group_size.DUO);
        Song song58 = new Song("Someone Like You","21","Adele",285, Language.ENGLISH, Genre.POP, Feeling.SADLY, Action.NOSTALGIA, 2011, Temp.SLOW, Group_size.SOLO);
        Song song59 = new Song("Happy","Girl","Pharrell Williams",233, Language.ENGLISH, Genre.POP, Feeling.HAPPY, Action.LEARNING, 2013, Temp.MEDIUM, Group_size.SOLO);
        Song song60 = new Song("Numb","Meteora","Linkin Park",186, Language.ENGLISH, Genre.ROCK, Feeling.AGGRESSIVE, Action.TRAINING, 2003, Temp.FAST, Group_size.DUO);
        Song song61 = new Song("Set Fire to the Rain","21","Adele",239, Language.ENGLISH, Genre.POP, Feeling.SADLY, Action.NOSTALGIA, 2011, Temp.MEDIUM, Group_size.SOLO);
        Song song62 = new Song("Ode to Joy","Symphony No. 9","Ludwig van Beethoven",581, Language.INSTRUMENTAL, Genre.CLASSIC, Feeling.EPIC, Action.LEARNING, 1824, Temp.MEDIUM, Group_size.CHOIR);
        Song song63 = new Song("Uptown Funk","Uptown Special","Mark Ronson ft. Bruno Mars",271, Language.ENGLISH, Genre.POP, Feeling.ENERGETICALLY, Action.PARTY, 2014, Temp.MEDIUM, Group_size.DUO);
        Song song64 = new Song("Blinding Lights","After Hours","The Weeknd",200, Language.ENGLISH, Genre.POP, Feeling.ENERGETICALLY, Action.PARTY, 2020, Temp.FAST, Group_size.SOLO);
        Song song65 = new Song("Тает дым","Температура","Morgenshtern",180, Language.RUSSIAN, Genre.HIPHOP, Feeling.AGGRESSIVE, Action.TRAINING, 2019, Temp.FAST, Group_size.SOLO);
        Song song66 = new Song("Paradise","Mylo Xyloto","Coldplay",280, Language.ENGLISH, Genre.ROCK, Feeling.EPIC, Action.DRIVING, 2011, Temp.MEDIUM, Group_size.QUARTET);
        Song song67 = new Song("Je T'aime","Les Années Barclay","Lara Fabian",250, Language.ENGLISH, Genre.CLASSIC, Feeling.MYSTICALLY, Action.SLEEPING, 2004, Temp.SLOW, Group_size.SOLO);
        Song song68 = new Song("Кукушка","Звезда по имени Солнце","Кино",219, Language.RUSSIAN, Genre.ROCK, Feeling.MYSTICALLY, Action.NOSTALGIA, 1989, Temp.MEDIUM, Group_size.QUARTET);
        Song song69 = new Song("Прошепчу вам тайны","Прошепчу вам тайны","Louna",237, Language.RUSSIAN, Genre.ROCK, Feeling.AGGRESSIVE, Action.TRAINING, 2019, Temp.FAST, Group_size.QUINTET);
        Song song70 = new Song("La Macarena","A mí me gusta","Los del Río",223, Language.SPANISH, Genre.POP, Feeling.HAPPY, Action.PARTY, 1995, Temp.FAST, Group_size.DUO);
        Song song71 = new Song("The Show Must Go On","Innuendo","Queen",268, Language.ENGLISH, Genre.ROCK, Feeling.EPIC, Action.WORKING, 1991, Temp.MEDIUM, Group_size.QUINTET);
        Song song72 = new Song("Wrecking Ball","Bangerz","Miley Cyrus",225, Language.ENGLISH, Genre.POP, Feeling.MYSTICALLY, Action.NOSTALGIA, 2013, Temp.SLOW, Group_size.SOLO);
        Song song73 = new Song("Zombie","No Need to Argue","The Cranberries",307, Language.ENGLISH, Genre.ROCK, Feeling.AGGRESSIVE, Action.DRIVING, 1994, Temp.MEDIUM, Group_size.QUARTET);
        Song song74 = new Song("Пачка сигарет","Москва","Ария",197 , Language.RUSSIAN, Genre.METAL, Feeling.AGGRESSIVE, Action.TRAINING, 1985, Temp.FAST, Group_size.QUINTET);
        Song song75 = new Song("Чайка","Песни тибетских лам","Мельница",335, Language.RUSSIAN, Genre.ROCK, Feeling.DREAMY, Action.WORKING, 2006, Temp.MEDIUM, Group_size.QUINTET);
        Song song76 = new Song("The Scientist","A Rush of Blood to the Head","Coldplay",309, Language.ENGLISH, Genre.ROCK, Feeling.SADLY, Action.NOSTALGIA, 2002, Temp.SLOW, Group_size.QUARTET);
        Song song77 = new Song("Bailando","Sex and Love","Enrique Iglesias feat. Gente de Zona and Descemer Bueno",269, Language.SPANISH, Genre.POP, Feeling.HAPPY, Action.PARTY, 2014, Temp.MEDIUM, Group_size.QUARTET);
        Song song78 = new Song("Stairway to Heaven","Led Zeppelin IV","Led Zeppelin",482, Language.ENGLISH, Genre.ROCK, Feeling.MYSTICALLY, Action.NOSTALGIA, 1971, Temp.SLOW, Group_size.QUARTET);
        Song song79 = new Song("Rolling in the Deep","21","Adele",228, Language.ENGLISH, Genre.POP, Feeling.AGGRESSIVE, Action.DRIVING, 2010, Temp.FAST, Group_size.SOLO);
        Song song80 = new Song("La Isla Bonita","True Blue","Madonna",228, Language.ENGLISH, Genre.POP, Feeling.HAPPY, Action.PARTY, 1986, Temp.FAST, Group_size.SOLO);
        Song song81 = new Song("My Immortal","Fallen","Evanescence",290, Language.ENGLISH, Genre.ROCK, Feeling.SADLY, Action.NOSTALGIA, 2003, Temp.SLOW, Group_size.QUINTET);
        Song song82 = new Song("Полковнику никто не пишет","Брутто","Кино",176, Language.RUSSIAN, Genre.ROCK, Feeling.ENERGETICALLY, Action.NOSTALGIA, 1988, Temp.FAST, Group_size.QUARTET);
        Song song83 = new Song("What a Wonderful World","What a Wonderful World","Louis Armstrong",142, Language.ENGLISH, Genre.JAZZ, Feeling.DREAMY, Action.NOSTALGIA, 1967, Temp.SLOW, Group_size.SOLO);
        Song song84 = new Song("Около тебя","Берега","Агата Кристи",273, Language.RUSSIAN, Genre.ROCK, Feeling.CALM, Action.NOSTALGIA, 1997, Temp.SLOW, Group_size.QUINTET);
        Song song85 = new Song("Billie Jean","Thriller","Michael Jackson",294, Language.ENGLISH, Genre.POP, Feeling.ENERGETICALLY, Action.PARTY, 1982, Temp.FAST, Group_size.SOLO);
        Song song86 = new Song("Believe","Believe","Cher",239, Language.ENGLISH, Genre.POP, Feeling.HAPPY, Action.PARTY, 1998, Temp.FAST, Group_size.SOLO);
        Song song87 = new Song("Трава у дома",null,"Земфира",288, Language.RUSSIAN, Genre.ROCK, Feeling.DREAMY, Action.NOSTALGIA,1999, Temp.MEDIUM, Group_size.QUINTET);
        Song song88 = new Song("Get Lucky","Random Access Memories","Daft Punk featuring Pharrell Williams",249, Language.ENGLISH, Genre.DISCO, Feeling.HAPPY, Action.PARTY, 2013, Temp.MEDIUM, Group_size.QUARTET);
        Song song89 = new Song("Thriller","Thriller","Michael Jackson",357, Language.ENGLISH, Genre.POP, Feeling.ENERGETICALLY, Action.PARTY, 1982, Temp.FAST, Group_size.SOLO);
        Song song90 = new Song("Листья желтые","Стены","Ария",272 , Language.RUSSIAN, Genre.METAL, Feeling.AGGRESSIVE, Action.TRAINING, 1989, Temp.FAST, Group_size.QUINTET);
        Song song91 = new Song("Thunderstruck","The Razors Edge","AC/DC",393, Language.ENGLISH, Genre.METAL, Feeling.ENERGETICALLY, Action.PARTY, 1990, Temp.FAST, Group_size.QUARTET);
        Song song92 = new Song("September","I Am","Earth, Wind & Fire",215, Language.ENGLISH, Genre.DISCO, Feeling.HAPPY, Action.PARTY, 1978, Temp.FAST, Group_size.QUINTET);
        Song song93 = new Song("Stayin' Alive","Saturday Night Fever","Bee Gees",297, Language.ENGLISH, Genre.DISCO, Feeling.ENERGETICALLY, Action.PARTY, 1977, Temp.FAST, Group_size.TRIO);
        Song song94 = new Song("Chop Suey!","Toxicity","System of a Down",210, Language.ENGLISH, Genre.METAL, Feeling.AGGRESSIVE, Action.WORKING, 2001, Temp.FAST, Group_size.QUARTET);
        Song song95 = new Song("Половинка","Земляничная поляна","Владимир Мигуля",194, Language.RUSSIAN, Genre.ROCK, Feeling.DREAMY, Action.NOSTALGIA, 2005, Temp.FAST, Group_size.SOLO);
        Song song96 = new Song("Take on Me","Hunting High and Low","A-ha",229, Language.ENGLISH, Genre.POP, Feeling.ENERGETICALLY, Action.DRIVING, 1984, Temp.FAST, Group_size.TRIO);
        Song song97 = new Song("Луна","Хранительница","Валерия",265, Language.RUSSIAN, Genre.POP, Feeling.CALM, Action.SLEEPING, 2001, Temp.SLOW, Group_size.SOLO);
        Song song98 = new Song("Lose Yourself","8 Mile: Music from and Inspired by the Motion Picture","Eminem",326, Language.ENGLISH, Genre.RAP, Feeling.ENERGETICALLY, Action.TRAINING, 2002, Temp.FAST, Group_size.SOLO);
        Song song99 = new Song("Godzilla","Music To Be Murdered By - Side B","Eminem, Juice WRLD",210, Language.ENGLISH, Genre.RAP, Feeling.ENERGETICALLY, Action.TRAINING, 2020, Temp.FAST, Group_size.DUO);
        Song song100 = new Song("Mockingbird","Curtain Call: The Hits","Eminem",230, Language.ENGLISH, Genre.RAP, Feeling.SADLY, Action.SLEEPING, 2005, Temp.SLOW, Group_size.SOLO);
        Song song101 = new Song("We Will Rock You", "News of the World", "Queen", 122, Language.ENGLISH, Genre.ROCK, Feeling.ENERGETICALLY, Action.PARTY, 1977, Temp.MEDIUM, Group_size.QUARTET);
        Song song102 = new Song("Zombie", "No Need to Argue", "The Cranberries", 308, Language.ENGLISH, Genre.ROCK, Feeling.AGGRESSIVE, Action.TRAINING, 1994, Temp.MEDIUM, Group_size.QUARTET);
        Song song103 = new Song("La Vie en Rose", "Édith Piaf", "Édith Piaf", 212, Language.FRENCH, Genre.JAZZ, Feeling.HAPPY, Action.NOSTALGIA, 1946, Temp.SLOW, Group_size.SOLO);
        Song song104 = new Song("Piano Man", "Piano Man", "Billy Joel", 341, Language.ENGLISH, Genre.ROCK, Feeling.CALM, Action.NOSTALGIA, 1973, Temp.MEDIUM, Group_size.SOLO);
        Song song105 = new Song("Crazy in Love", "Dangerously in Love", "Beyoncé feat. Jay-Z", 235, Language.ENGLISH, Genre.POP, Feeling.ENERGETICALLY, Action.PARTY, 2003, Temp.FAST, Group_size.DUO);
        Song song106 = new Song("Bésame Mucho", "Consuelo Velázquez", "Consuelo Velázquez", 191, Language.SPANISH, Genre.INDY, Feeling.HAPPY, Action.DRIVING, 1941, Temp.SLOW, Group_size.SOLO);
        Song song107 = new Song("Du", "Good", "Cro", 228, Language.GERMAN, Genre.HIPHOP, Feeling.HAPPY, Action.PARTY, 2011, Temp.MEDIUM, Group_size.SOLO);
        Song song108 = new Song("Black Dog", "Led Zeppelin IV", "Led Zeppelin", 296, Language.ENGLISH, Genre.ROCK, Feeling.ENERGETICALLY, Action.DRIVING, 1971, Temp.FAST, Group_size.QUARTET);
        Song song109 = new Song("Somebody That I Used to Know", "Making Mirrors", "Gotye feat. Kimbra", 244, Language.ENGLISH, Genre.POP, Feeling.SADLY, Action.NOSTALGIA, 2011, Temp.SLOW, Group_size.DUO);
        Song song110 = new Song("Wannabe", "Spice", "Spice Girls", 174, Language.ENGLISH, Genre.POP, Feeling.HAPPY, Action.PARTY, 1996, Temp.FAST, Group_size.QUARTET);
        Song song111 = new Song("Stand by Me", "Ben E. King", "Ben E. King", 180, Language.ENGLISH, Genre.JAZZ, Feeling.HAPPY, Action.NOSTALGIA, 1961, Temp.SLOW, Group_size.SOLO);


        PlayList playList = new PlayList();
        playList.addSong(song1);
        playList.addSong(song2);
        playList.addSong(song3);
        playList.addSong(song4);
        playList.addSong(song5);
        playList.addSong(song6);
        playList.addSong(song7);
        playList.addSong(song8);
        playList.addSong(song9);
        playList.addSong(song10);
        playList.addSong(song11);
        playList.addSong(song12);
        playList.addSong(song13);
        playList.addSong(song14);
        playList.addSong(song15);
        playList.addSong(song16);
        playList.addSong(song17);
        playList.addSong(song18);
        playList.addSong(song19);
        playList.addSong(song20);
        playList.addSong(song21);
        playList.addSong(song22);
        playList.addSong(song23);
        playList.addSong(song24);
        playList.addSong(song25);
        playList.addSong(song26);
        playList.addSong(song27);
        playList.addSong(song28);
        playList.addSong(song29);
        playList.addSong(song30);
        playList.addSong(song31);
        playList.addSong(song32);
        playList.addSong(song33);
        playList.addSong(song34);
        playList.addSong(song35);
        playList.addSong(song36);
        playList.addSong(song37);
        playList.addSong(song38);
        playList.addSong(song39);
        playList.addSong(song40);
        playList.addSong(song41);
        playList.addSong(song42);
        playList.addSong(song43);
        playList.addSong(song44);
        playList.addSong(song45);
        playList.addSong(song46);
        playList.addSong(song47);
        playList.addSong(song48);
        playList.addSong(song49);
        playList.addSong(song50);
        playList.addSong(song51);
        playList.addSong(song52);
        playList.addSong(song53);
        playList.addSong(song54);
        playList.addSong(song55);
        playList.addSong(song56);
        playList.addSong(song57);
        playList.addSong(song58);
        playList.addSong(song59);
        playList.addSong(song60);
        playList.addSong(song61);
        playList.addSong(song62);
        playList.addSong(song63);
        playList.addSong(song64);
        playList.addSong(song65);
        playList.addSong(song66);
        playList.addSong(song67);
        playList.addSong(song68);
        playList.addSong(song69);
        playList.addSong(song70);
        playList.addSong(song71);
        playList.addSong(song72);
        playList.addSong(song73);
        playList.addSong(song74);
        playList.addSong(song75);
        playList.addSong(song76);
        playList.addSong(song77);
        playList.addSong(song78);
        playList.addSong(song79);
        playList.addSong(song80);
        playList.addSong(song81);
        playList.addSong(song82);
        playList.addSong(song83);
        playList.addSong(song84);
        playList.addSong(song85);
        playList.addSong(song86);
        playList.addSong(song87);
        playList.addSong(song88);
        playList.addSong(song89);
        playList.addSong(song90);
        playList.addSong(song91);
        playList.addSong(song92);
        playList.addSong(song93);
        playList.addSong(song94);
        playList.addSong(song95);
        playList.addSong(song96);
        playList.addSong(song97);
        playList.addSong(song98);
        playList.addSong(song99);
        playList.addSong(song100);
        playList.addSong(song101);
        playList.addSong(song102);
        playList.addSong(song103);
        playList.addSong(song104);
        playList.addSong(song105);
        playList.addSong(song106);
        playList.addSong(song107);
        playList.addSong(song108);
        playList.addSong(song109);
        playList.addSong(song110);
        playList.addSong(song111);


        return playList;
    }
}
